---
title: "coups"
author: "Nidal"
date: "4/1/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)

library(tidyverse)
library(gifski)
library(janitor)
library(gganimate)
library(readxl)
library(infer)

coups <- read_excel("raw-data/Coupdata.xls") %>% 
  clean_names()

polity <- read_excel("raw-data/polity_iv.xls") %>% 
  clean_names()
```

```{r clean_and_join}

clean_coups <- coups %>% 
  select(year_of_event, cow_code, country_where_action_occurred, type_of_coup, 
         realized_coup, unrealized)

clean_polity <- polity %>% 
  select(year, ccode, country, scode, polity) %>% 
  filter(year >= "1946") %>% 
  filter(polity != "-88") %>% 
  filter(polity != "-77") %>% 
  filter(polity != "-66")

join_copo <- clean_coups %>% 
  inner_join(clean_polity, by = c("year_of_event" = "year", 
                                  "country_where_action_occurred" = "country"))
```

```{r sample}

coup_data <- join_copo %>%
  rep_sample_n(size = nrow(coup_data), reps = 50, replace = TRUE) %>% 
  group_by(polity, realized_coup, type_of_coup, replicate) %>% 
  count(type_of_coup) %>% 
  mutate(number = n)


```

```{r plot}

ggplot(coup_data, aes(x = polity, y = number, color = type_of_coup)) + 
  geom_jitter(width = 0.5, height = 0.5) +
  theme_classic()
```

