---
title: "countries"
author: "Nidal"
date: "4/17/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)

library(tidyverse)
library(gifski)
library(janitor)
library(gganimate)
library(readxl)
library(infer)

# For the treatment graphic where i can see if a country's number of coups
# inreased or decreased after becoming democratic.

coups <- read_excel("raw-data/Coupdata.xls") %>% 
  clean_names()

polity <- read_excel("raw-data/polity_iv.xls") %>% 
  clean_names()


```

```{r}

argentina <- polity %>% 
  filter(country == "Argentina") %>% 
  select(year, ccode, country, polity) %>% 
  filter(year >= "1946") %>% 
  filter(polity != "-88") %>% 
  filter(polity != "-77") %>% 
  filter(polity != "-66")

argen_coup <- coups %>% 
  filter(cow_code == 160) %>% 
  select(year_of_event, cow_code, country_where_action_occurred, type_of_coup, 
         realized_coup, unrealized) %>% 
  group_by(year_of_event) %>% 
  count()

full_argen <- full_join(argentina, argen_coup, by = c("year" = "year_of_event"))

full_argen$n <- full_argen$n %>% 
  replace_na(0)

full_argen <- full_argen %>% 
  filter(!is.na(ccode)) %>% 
  filter(!is.na(country)) %>% 
  filter(!is.na(polity))

ggplot(full_argen, aes(x = polity)) +
  geom_jitter(aes(y = n), size = 1) +
  geom_smooth(aes(y = n), color = "blue", se = FALSE) 
 

```

