---
title: "coups"
author: "Nidal"
date: "4/1/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)

library(tidyverse)
library(gifski)
library(janitor)
library(gganimate)
library(readxl)
library(infer)
library(readr)
library(broom)
library(skimr)

# For my main graphic

coups <- read_excel("raw-data/Coupdata.xls") %>% 
  clean_names()

polity <- read_excel("raw-data/polity_iv.xls") %>% 
  clean_names()


```

```{r clean_and_join}

clean_coups <- coups %>% 
  select(year_of_event, cow_code, country_where_action_occurred, type_of_coup, 
         realized_coup, unrealized) %>% 
  group_by(year_of_event, country_where_action_occurred) %>% 
  count()

attempt_coups <- coups %>% 
  select(year_of_event, cow_code, country_where_action_occurred, type_of_coup) %>% 
  filter(type_of_coup == "attempt")

comp_coups <- coups %>% 
  select(year_of_event, cow_code, country_where_action_occurred, type_of_coup) %>% 
  filter(type_of_coup == "coup")

consp <- coups %>% 
  select(year_of_event, cow_code, country_where_action_occurred, type_of_coup) %>% 
  filter(type_of_coup == "conspiracy")

clean_polity <- polity %>% 
  select(year, ccode, country, scode, democ, autoc, polity) %>% 
  filter(year >= "1946") %>% 
  filter(polity != "-88", 
         polity != "-77",
         polity != "-66") %>% 
  filter(democ != "-88",
         democ != "-77",
         democ != "-66") %>% 
  filter(autoc != "-88",
         autoc != "-77",
         autoc != "-66")

join_copo <- clean_polity %>% 
  full_join(clean_coups, by = c("year" = "year_of_event", 
                                "country" = "country_where_action_occurred"))

join_attempt <- clean_polity %>% 
  full_join(attempt_coups, by = c("year" = "year_of_event", 
                                "country" = "country_where_action_occurred")) %>% 
  mutate(attempt_bin = case_when(type_of_coup == "attempt" ~ '1',
                                 TRUE ~ '0')) %>% 
  select(-cow_code) %>% 
  mutate(region = case_when(ccode %in% 2:70 ~ 'NA',
                            ccode %in% 80:165 ~ 'SA',
                            ccode %in% 200:395 ~ 'EU',
                            ccode %in% 402:591 ~ 'AFR',
                            ccode %in% 615:698 ~ 'ME',
                            ccode %in% 700:860 ~ 'AS',
                            ccode %in% 900:990 ~ 'OC')) %>% 
  filter(!is.na(region))

join_attempt$attempt_bin <- as.numeric(join_attempt$attempt_bin)

join_attempt %>% 
  group_by(polity) %>% 
  summarize(perc_att = mean(attempt_bin),
            emp = qlogis(perc_att)) %>% 
  ggplot(aes(x = polity, y = emp)) +
  geom_point() 


join_copo$n <- join_copo$n %>% 
  replace_na(0) 

join_copo <- join_copo %>% 
  filter(!is.na(democ)) %>% 
  filter(!is.na(autoc)) %>% 
  filter(!is.na(polity))

join_copo <- join_copo %>% 
  mutate(region = case_when(ccode %in% 2:70 ~ 'NA',
                            ccode %in% 80:165 ~ 'SA',
                            ccode %in% 200:395 ~ 'EU',
                            ccode %in% 402:591 ~ 'AFR',
                            ccode %in% 615:698 ~ 'ME',
                            ccode %in% 700:860 ~ 'AS',
                            ccode %in% 900:990 ~ 'OC')) %>% 
  filter(!is.na(region))

ggplot(join_copo, aes(x = polity, y = n, color = region, fill = region)) +
  geom_area(stat = "identity", alpha = 0.6)

```






