
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE)

library(tidyverse)
library(gifski)
library(janitor)
library(gganimate)
library(readxl)
library(infer)

coups <- read_excel("raw-data/Coupdata.xls") %>% 
  clean_names()

polity <- read_excel("raw-data/polity_iv.xls") %>% 
  clean_names()
```

```{r}

clean_coups <- coups %>% 
  select(year_of_event, cow_code, country_where_action_occurred, type_of_coup, 
         realized_coup, unrealized)

clean_polity <- polity %>% 
  select(year, ccode, country, scode, polity) %>% 
  filter(year >= "1946") %>% 
  filter(polity != "-88") %>% 
  filter(polity != "-77") %>% 
  filter(polity != "-66")

join_copo <- clean_coups %>% 
  inner_join(clean_polity, by = c("year_of_event" = "year", 
                                  "country_where_action_occurred" = "country"))

```

```{r}

set.seed(2)

coups <- join_copo %>% 
  group_by(polity) %>% 
  summarize(sum = sum(realized_coup + unrealized)) 
  
coup_data <- join_copo %>%
  group_by(polity, realized_coup, unrealized, type_of_coup) %>% 
  summarize(num = sum(realized_coup + unrealized)) %>% 
  mutate(number = num)
  
```

```{r}


simple_graph <- ggplot(coup_data, 
                       aes(x = polity, y = number, color = type_of_coup)) + 
  geom_jitter(width = 0.5, height = 0.5) +
  labs(
    title = "Number of Coups d'Etat by Regime Type",
    subtitle = "Including attempts and conspiracies",
    x = "Polity IV scale (-10 is least democratic, +10 is most democratic)",
    y = "Number of Coups d'Etat",
    color = "Type of Coup",
    caption = "Data from the Polity IV Project and the Coup d'Etat Project") +
  theme_classic()

simple_graph +
  transition_manual(type_of_coup)
```

