---
title: "regimes"
author: "Nidal"
date: "4/7/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE)

library(tidyverse)
library(gifski)
library(janitor)
library(gganimate)
library(readxl)
library(infer)

# For the relationship between regime type and coup success

regime_polity <- read_excel("raw-data/polity_iv.xls") %>% 
  clean_names() %>% 
  select(year, ccode, country, scode, polity) %>% 
  filter(year >= "1946") %>% 
  filter(polity != "-88") %>% 
  filter(polity != "-77") %>% 
  filter(polity != "-66")

coups <- read_excel("raw-data/Coupdata.xls") %>% 
  clean_names()

regime_coups <- coups %>% 
  select(cow_code, country_where_action_occurred, year_of_event, month_of_event, day_of_event, type_of_coup, realized_coup, unrealized, military_coup, rebel_coup, palace_coup)

autocracy <- read_excel("raw-data/autocracies.xlsx") %>% 
  clean_names() %>% 
  select(cowcode, gwf_country, gwf_regimetype, gwf_startyr, gwf_endyr, gwf_howend)

democracy <- read_excel("raw-data/all_regimes.xls") %>% 
  clean_names() %>% 
  filter(regime_type == "democracy") %>% 
  select(country, regime_type)


```

```{r monarchy}

monarchy <- autocracy %>% 
  filter(gwf_regimetype == "monarchy")

```

```{r military}

military <- autocracy %>% 
  filter(gwf_regimetype == "military")

```

